"""Centralized API error code constants.

Use these constants in route error payloads and service adapters to keep
a stable, searchable error taxonomy across domains.
"""

from __future__ import annotations

# Generic platform-level codes
VALIDATION_ERROR = "VALIDATION_ERROR"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
UPSTREAM_ERROR = "UPSTREAM_ERROR"

# Celonis domain codes
CELONIS_TOOL_NOT_FOUND = "CELONIS_TOOL_NOT_FOUND"
CELONIS_ORG_SCOPE_MISMATCH = "CELONIS_ORG_SCOPE_MISMATCH"
CELONIS_TOKEN_REQUIRED = "CELONIS_TOKEN_REQUIRED"
CELONIS_QUEST_NOT_FOUND = "CELONIS_QUEST_NOT_FOUND"
CELONIS_DEPLOYMENT_REQUEST_REQUIRED = "CELONIS_DEPLOYMENT_REQUEST_REQUIRED"
CELONIS_DEPLOYMENT_REQUEST_INVALID = "CELONIS_DEPLOYMENT_REQUEST_INVALID"
CELONIS_DEPLOYMENT_REQUEST_NOT_FOUND = "CELONIS_DEPLOYMENT_REQUEST_NOT_FOUND"
CELONIS_DEPLOYMENT_CLIENT_MISMATCH = "CELONIS_DEPLOYMENT_CLIENT_MISMATCH"
CELONIS_DEPLOYMENT_NOT_APPROVED = "CELONIS_DEPLOYMENT_NOT_APPROVED"
CELONIS_DEPLOYMENT_PACKAGE_MISMATCH = "CELONIS_DEPLOYMENT_PACKAGE_MISMATCH"
CELONIS_TOOL_INVOCATION_ERROR = "CELONIS_TOOL_INVOCATION_ERROR"
CELONIS_TOOL_UPSTREAM_ERROR = "CELONIS_TOOL_UPSTREAM_ERROR"
